title: "CurienDR-Altair's Website"
description: >- # this means to ignore newlines until "baseurl:"
  Content I can share through my website.
baseurl: "/curiendr-altair.github.io/docs" # the subpath of your site, e.g. /blog
url: "https://curiendr-altair.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: curiendr-altair.github.io
github_username:  curiendr-altair
plugins:
  - jekyll-feed
  - jekyll-sitemap